id = "hocon"
name = "HOCON"
description = "HOCON (Human-Optimized Config Object Notation) language support"
version = "0.2.0"
schema_version = 1
authors = ["Jens Kouros <jens.kouros@posteo.de>"]
repository = "https://github.com/tomatitito/hocon-zed-extension"

[grammars.hocon]
repository = "https://github.com/tomatitito/tree-sitter-hocon"
commit = "8958da3c6b7e02db38ed86706a68add87325a7f0"
