id = "hocon"
name = "HOCON"
description = "HOCON (Human-Optimized Config Object Notation) language support"
version = "0.1.0"
schema_version = 1
authors = ["Jens Kouros <jens.kouros@posteo.de>"]
repository = "https://github.com/tomatitito/hocon-zed-extension"

[grammars.hocon]
repository = "https://github.com/tomatitito/tree-sitter-hocon"
commit = "master"

# [[languages]]
# name = "hocon"
# grammar = "hocon"
# file_types = ["conf", "hocon"]
# scope = "source.hocon"
# language_id = "hocon"
# comment_tokens = ["//", "#", "/*", "*/"]

# Removed language server section for now to focus on syntax highlighting
# Will add it back when implementing LSP functionality
