name = "HOCON"
grammar = "hocon"
path_suffixes = ["conf", "hocon"]
line_comments = ["//", "#"]
block_comment = ["/*", "*/"]
autoclose_before = ")]},*/#"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] }
]

# Optional: Language server configuration
[language_servers.hocon-lsp]
name = "hocon-lsp"
command = "hocon-lsp"
args = ["--stdio"]

# Language server initialization options
[language_servers.hocon-lsp.initialization_options]
# Add any LSP-specific configuration here